Class {
	#name : 'OCRERSScatterPlot',
	#superclass : 'RSScatterPlot',
	#category : 'OCDbgAnalysis-Metrics',
	#package : 'OCDbgAnalysis',
	#tag : 'Metrics'
}

{ #category : 'rendering' }
OCRERSScatterPlot >> maxValueX [
	^5
]

{ #category : 'rendering' }
OCRERSScatterPlot >> maxValueY [ 
	^4500
]

{ #category : 'rendering' }
OCRERSScatterPlot >> minValueX [
	^1
]

{ #category : 'rendering' }
OCRERSScatterPlot >> minValueY [ 
	^0
]
